anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

ApiController:
    resource: '../src/Anaxago/CoreBundle/Controller/ApiController.php'
    type:     annotation

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }