<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * InvestmentProjectSimulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestmentProjectSimulationRepository extends \Doctrine\ORM\EntityRepository
{
}
