<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * ProjectMarkInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectMarkInterestRepository extends \Doctrine\ORM\EntityRepository
{
}
